rm "$HOME/.vimrc"
rm "$HOME/.config/starship.toml"
rm "$HOME/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
rm "$HOME/.config/whkdrc"
rm -r "$HOME/.config/yasb/"
rm -r "$HOME/.config/komorebi/"