#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons
ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored
FONT="Hack Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=5 # All paddings use this value

# Setting up the general bar appearance of the bar
bar=(
  height=38
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  margin=-2
  padding_right=10
  padding_left=10
)
sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  padding_left=$PADDINGS
  padding_right=$PADDINGS
  icon.right_padding=$PADDINGS
  icon.left_padding=$PADDINGS
  label.font="$FONT:Bold:14.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=5 
  background.padding_right=5 
  background.padding_left=5
  background.color=0x9924273a
  popup.background.border_width=2
  popup.background.corner_radius=5
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${defaults[@]}"

# Left
# source $ITEM_DIR/apple.sh
source "$ITEM_DIR/calendar.sh"
source $ITEM_DIR/front_app.sh

# Right
source $ITEM_DIR/spaces.sh

sketchybar --update

echo "sketchybar configuation loaded.."
