#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger          window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/      yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/    yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger          windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger        windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^(百度网盘|Slack|foobar2000|LuLu|Calculator|Software             Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo           Booth|Archive Utility|Python|App Store|Steam|Activity         Monitor|微信|飞书|腾讯会议)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$"                                title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$"                                title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Priv acy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information"              title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$"              title="Select file to save to" manage=off

echo "yabai configuration loaded.."
